// Shared brief for writing and for the independent editorial assessment.
export const contentPolicy=`Henry wants a recognisable watch concierge account, not a feed of random watch questions.
PUNCTUATION: Never use em dashes (Unicode U+2014 or its presentation variants) in post text. Rewrite the sentence using commas, colons, parentheses or periods. This is a hard rule for both drafting and editorial review; reject any draft containing an em dash.
POSITIONING: Demonstrate practical watch-buying expertise and explain the benefits of a reputable grey-market dealer: choice of the exact watch, clear transaction terms, and comparison of total acquisition cost. Teach buyers how to assess condition, seller reputation, provenance, service history, and warranty terms. Be specific and balanced; do not imply all grey-market sellers are trustworthy. Never claim Rolex itself forces bundled purchases or present an anecdote as a universal authorized-dealer policy.
QUALITY BAR: Each post must give a specific buyer a concrete takeaway, a defensible watch comparison/detail, or a clear and supported point of view. Start with the substance. If the same wording could advertise cars, sneakers or any luxury product by swapping the noun, it is too generic.
Avoid prompts such as 'What is your favourite watch?', vague wrist-size advice, motivational luxury quotes, empty hot takes and questions added solely to collect replies. A useful question must narrow a real buying decision and include Henry's documented perspective or a concrete decision framework.
Use Henry's verified first-hand notes, buyer questions and approved past content as voice evidence. An RSS headline supplies a research lead, not Henry's opinion or proof of a claim. Never convert a third-party story into 'I sourced', 'my client' or 'I wore'. Never invent a preference, sale, client outcome or availability.
For each draft's editorial note, identify its audience, its ONE job (reach, useful advice, authority, meaningful discussion, or a sourcing inquiry), the specific takeaway, and the source or Henry note supporting it. Lack of evidence must be explicit. The sourcing pitch is at most one of five posts; the others must be worth reading without buying anything.
Five posts per day is a ceiling and target, not a reason to publish filler. A weak draft must be held. Do not claim an angle will go viral or that engagement equals leads. Learn from measured qualified inquiries and use engagement only as supporting evidence.`;
