(function () {
    'use strict';
    var timer, generation=0, active=false, busy=false, data, root, screen='queue', filter='all';
    var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});};
    var date=function(v){return v?new Date(v).toLocaleString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})+' ET':'—';};
    var button=function(label,action,id,extra){return '<button type="button" class="btn ghost" data-social-action="'+action+'"'+(id?' data-id="'+esc(id)+'"':'')+(extra?' '+extra:'')+'>'+label+'</button>';};
    var field=function(label,name,value,type,extra){return '<label for="social-'+name+'">'+label+'</label><input class="ctl" id="social-'+name+'" name="'+name+'" type="'+(type||'text')+'" value="'+esc(value)+'" '+(extra||'')+'>';};
    var checked=function(v){return v?' checked':'';};
    var localTime=function(v){return v?new Date(Date.parse(v)-new Date(v).getTimezoneOffset()*60000).toISOString().slice(0,16):'';};
    function stop(){active=false;generation++;clearInterval(timer);if(root){root.onclick=null;root.onsubmit=null;root.onkeydown=null;}}
    function error(message){var box=root&&root.querySelector('#social-error');if(box){box.textContent=message;box.hidden=false;}}
    function notice(message){var box=root&&root.querySelector('#social-notice');if(box){box.textContent=message;box.hidden=false;}}
    function shell(d,content){
        var tabs=[['queue','Queue'],['research','Research'],['results','Performance'],['settings','Connections & settings']];
        return '<div class="social"><div class="bar"><h2>Social publishing</h2><span class="pill '+(!d.paused?'on':'')+'">'+(d.paused?'Paused':'Active')+'</span><span class="pill">'+(d.autonomy==='autonomous'?'Autonomous':'Review each post')+'</span><div class="grow"></div>'+button('Refresh','refresh')+button(d.paused?'Resume publishing':'Pause publishing',d.paused?'resume':'pause')+'</div>'+
            (d.preview?'<p class="social-preview">Local preview of your existing admin · publishing changes are disabled here.</p>':'')+
            '<div class="social-subnav" aria-label="Social publishing views">'+tabs.map(function(t){return button(t[1],'screen',null,'data-screen="'+t[0]+'" aria-pressed="'+(screen===t[0])+'"');}).join('')+'</div><p id="social-error" class="err" role="alert" hidden></p><p id="social-notice" class="social-note" role="status" hidden></p>'+content+'</div>';
    }
    function jobs(d){var rows=(d.workspace.jobs||[]).filter(function(j){return j.key.indexOf('admin:')===0&&['queued','running','failed'].indexOf(j.status)!==-1;});return rows.map(function(j){return '<p class="social-job '+(j.status==='failed'?'err':'count')+'">'+esc(j.key.replace('admin:','').replace(':',' · '))+' · '+esc(j.status)+(j.error?' · '+esc(j.error):'')+'</p>';}).join('');}
    function queue(d){
        var verified=d.posts.filter(function(p){return p.delivery_status==='verified';}).length;
        var awaiting=d.posts.filter(function(p){return ['draft','uncertain','failed','expired'].indexOf(p.status)!==-1||p.delivery_status==='unverified';}).length;
        var rows=d.posts.filter(function(p){return filter==='all'||(filter==='review'?['draft','uncertain','failed','expired'].indexOf(p.status)!==-1:p.status===filter);});
        return '<div class="social-grid"><section class="social-panel"><span class="count">X account</span><h3>'+esc(d.account?'@'+d.account.username:'Not connected')+'</h3><p>'+(d.account?'Account ID '+esc(d.account.id):'Add credentials in Connections & settings.')+'</p><p class="count">Verified: '+date(d.account&&d.account.verifiedAt)+'</p>'+(d.account?button('Verify account','verify-account'):button('Connect account','screen',null,'data-screen="settings"'))+'</section>'+
            '<section class="social-panel"><span class="count">Publishing worker</span><h3>'+(d.worker.healthy?'Checking the queue':'Offline or delayed')+'</h3><p>Heartbeat: '+date(d.worker.heartbeat)+'</p><p>Last state save: '+date(d.worker.lastSweep)+'</p></section>'+
            '<section class="social-panel"><span class="count">Next post</span><h3>'+esc(d.nextPost?date(d.nextPost.scheduled_at):'No posts queued')+'</h3><p>'+verified+' verified · '+awaiting+' need attention</p><p class="count">X estimate: $'+Number(d.estimatedSpend).toFixed(2)+' / $'+d.monthlyBudget+'</p></section></div>'+jobs(d)+
            '<div class="bar">'+button('New post','new')+button('Prepare a day','generate')+'<div class="grow"></div>'+[['all','All'],['review','For review'],['scheduled','Scheduled'],['posted','Published']].map(function(f){return button(f[1],'filter',null,'data-filter="'+f[0]+'" aria-pressed="'+(filter===f[0])+'"');}).join('')+'</div>'+
            '<section class="social-panel"><h3>Publishing queue & delivery</h3><p class="social-note">Five daily slots are a target. Weak or unsupported drafts stay held; starter drafts are layout examples, not an approved content plan.</p><p>Verified means the post was fetched back from X and its author and text matched. Accepted posts awaiting that check are shown separately.</p><div class="social-table-wrap"><table class="social-table"><thead><tr><th>Post</th><th>Schedule</th><th>Status</th><th>Delivery</th><th>Actions</th></tr></thead><tbody>'+rows.map(function(p){
                var editable=['draft','scheduled','failed','expired'].indexOf(p.status)!==-1;
                var actions=editable?button('Edit','edit',p.id):'';
                if(['draft','failed','expired'].indexOf(p.status)!==-1)actions+=button('Approve','approve',p.id);
                if(p.status==='scheduled')actions+=button('Unschedule','unschedule',p.id);
                if(editable)actions+=button('Reject','reject',p.id);
                if(p.status==='uncertain')actions+=button('Reconcile','resolve',p.id);
                if(p.delivery_status==='unverified')actions+=button('Recheck','recheck',p.id);
                var fullPost=d.workspace.posts.find(function(item){return item.id===p.id;});var photo=fullPost&&d.workspace.media.find(function(m){return m.id===fullPost.media_id;});
                var delivery=p.delivery_status==='verified'?'Verified':p.delivery_status==='unverified'?'Could not verify':p.status==='posted'?'Accepted · check pending':'—';
                return '<tr><td><div class="count">'+esc(p.category)+'</div><p class="social-post">'+esc(p.body)+'</p>'+(photo?'<div class="social-queue-photo">'+(photo.source_url?'<img src="'+esc(photo.source_url)+'" alt="'+esc(photo.alt)+'" loading="lazy">':'')+'<p class="social-note">Image: '+esc(photo.alt)+'</p></div>':'')+(p.error?'<p class="err">'+esc(p.error)+'</p>':'')+(p.editorial_reasons.length?'<p class="social-note">'+esc(p.editorial_reasons.join(' ').replace('Edited by Henry;', 'Edited in admin;'))+'</p>':'')+'</td><td>'+date(p.scheduled_at)+'</td><td>'+esc(p.status)+(p.auto_approved?'<p class="count">Automatically checked</p>':'')+'</td><td>'+delivery+(p.verified_at?'<p class="count">'+date(p.verified_at)+'</p>':'')+(p.url?'<p><a href="'+esc(p.url)+'" target="_blank" rel="noopener noreferrer">View on X ↗</a></p>':'')+(p.verification_error?'<p class="err">'+esc(p.verification_error)+'</p>':'')+'</td><td><div class="social-actions">'+actions+'</div></td></tr>';
            }).join('')+(rows.length?'':'<tr><td colspan="5">No posts in this view.</td></tr>')+'</tbody></table></div></section>'+
            '<section class="social-panel"><h3>Recent activity</h3>'+d.events.slice(0,10).map(function(e){return '<div class="social-event"><span class="count">'+date(e.created_at)+'</span><p>'+esc(e.message)+'</p></div>';}).join('')+'</section>';
    }
    function research(d){var w=d.workspace;return jobs(d)+'<div class="bar">'+button('Add a note or source','add-source')+button('Add feed','add-feed')+button('Refresh feeds','refresh-feeds')+'</div><section class="social-panel"><h3>Research feeds</h3>'+w.feeds.map(function(f){return '<div class="social-row"><div><strong>'+esc(f.name)+'</strong><p class="count">'+esc(f.error||'Last checked: '+date(f.checked_at))+'</p></div>'+button('Remove','remove-feed',f.id)+'</div>';}).join('')+'</section><section class="social-panel"><h3>Sources & your perspective</h3><p>Verify claims against the original source. Your notes supply the preferences and first-hand experience used in drafts.</p>'+w.sources.map(function(s){return '<div class="social-row"><div><h3>'+(s.url?'<a href="'+esc(s.url)+'" target="_blank" rel="noopener noreferrer">'+esc(s.title)+' ↗</a>':esc(s.title))+'</h3><p>'+esc(s.excerpt)+'</p><span class="pill '+(s.verified?'on':'')+'">'+(s.verified?'Verified':'Unverified')+'</span></div>'+button(s.verified?'Mark unverified':'I checked this source','verify-source',s.id)+'</div>';}).join('')+'</section>';}
    function performance(d){var posts=d.workspace.posts.filter(function(p){return p.status==='posted';});return '<div class="bar">'+button('Sync X metrics','metrics')+'</div><section class="social-panel"><h3>Post performance</h3><p>Use qualified inquiries alongside engagement when choosing future angles. No results are assumed before they are measured.</p><div class="social-table-wrap"><table class="social-table"><thead><tr><th>Post</th><th>Impressions</th><th>Likes</th><th>Replies</th><th>Reposts</th></tr></thead><tbody>'+posts.map(function(p){var m=p.metrics||{};return '<tr><td>'+esc(p.body)+'</td><td>'+esc(m.impression_count==null?'—':m.impression_count)+'</td><td>'+esc(m.like_count==null?'—':m.like_count)+'</td><td>'+esc(m.reply_count==null?'—':m.reply_count)+'</td><td>'+esc(m.retweet_count==null?'—':m.retweet_count)+'</td></tr>';}).join('')+(posts.length?'':'<tr><td colspan="5">No published posts yet.</td></tr>')+'</tbody></table></div></section><section class="social-panel"><h3>Attributed inquiries</h3><p>'+d.leads.map(function(l){return esc(l.stage)+': '+l.count;}).join(' · ')+'</p><p class="count">Website form attribution still needs to be connected. The existing Leads tab continues to hold your website leads.</p></section>';}
    function settings(d){var w=d.workspace,s=w.settings,c=w.connections;return '<div class="social-grid social-two"><section class="social-panel"><h3>Connections</h3><p>'+esc(c.x?'Connected as @'+c.x.username:'X is not connected.')+'</p>'+(c.x?button('Disconnect X','disconnect'):button('Connect @dialedbyh','connect'))+'<form data-social-form="integrations">'+field('OpenAI API key','openaiKey','','password','autocomplete="new-password" placeholder="'+(c.ai?'Saved; leave blank to keep':'Add API key')+'"')+field('Drafting model','model',c.model)+field('X OAuth client ID','xClientId','','text','autocomplete="off" placeholder="'+(c.xConfigured?'Saved; leave blank to keep':'From your X developer app')+'"')+field('X OAuth client secret','xClientSecret','','password','autocomplete="new-password"')+'<p class="social-note">Credentials are encrypted on the server and never returned to this page.</p><button class="btn" type="submit">Save connections</button></form><label>X callback URL</label><p class="social-code">'+esc(c.callback)+'</p><p class="social-note">Authorization returns you to this website admin.</p></section>'+
            '<section class="social-panel"><h3>Editorial & schedule</h3>'+button(d.autonomy==='autonomous'?'Require individual approval':'Enable autonomous mode','mode')+'<p>'+(d.autonomy==='autonomous'?'Eligible drafts are checked and scheduled automatically. Held drafts and human edits need your review.':'Drafts require individual approval before publishing.')+'</p><form data-social-form="settings"><label for="social-voice">Your voice</label><textarea class="ctl" id="social-voice" name="voice" rows="6" required>'+esc(s.voice)+'</textarea>'+'<label>Five daily slots · Eastern time</label><div class="social-times">'+s.slots.map(function(t,i){return '<input class="ctl" name="slot'+i+'" type="time" value="'+t+'" aria-label="Daily slot '+(i+1)+'" required>';}).join('')+'</div><label class="social-check"><input type="checkbox" name="autoGenerate"'+checked(s.autoGenerate)+'>Prepare tomorrow’s drafts after 6 PM Eastern</label><label class="social-check"><input type="checkbox" name="autoSiteImages"'+checked(s.autoSiteImages!==false)+'>Match catalogue photos to exact references in new AI drafts</label><p class="social-note">Requires a unique reference and brand match. Ambiguous matches stay text-only. Avoids reusing a photograph within 14 days; edited drafts keep your image choice.</p>'+field('Monthly X estimate limit (USD)','monthlyXBudget',s.monthlyXBudget,'number','min="1" max="500" required')+'<p class="social-note">At least 75 minutes between posts. Existing drafts retain their scheduled times.</p><button class="btn" type="submit">Save settings</button></form></section></div><section class="social-panel"><h3>Reddit · not connected</h3><p>'+esc(d.reddit.reason)+'</p></section>';}
    function setup(){
        return '<div class="social"><div class="bar"><h2>Social publishing</h2><span class="pill">Setup required</span></div><section class="social-panel"><h3>Publishing database unavailable</h3><p>'+esc(data.reason)+'</p><p>The publisher runs on this website’s Vercel hosting. No separate service address is needed.</p>'+button('Check connection','refresh')+'</section></div>';
    }
    function paint(){if(!data.configured){root.innerHTML=setup();return;}root.innerHTML=shell(data,({queue:queue,research:research,results:performance,settings:settings})[screen](data));}

    function form(title,kind,body,post){root.innerHTML=shell(data,'<section class="social-panel social-editor"><div class="bar"><h3>'+title+'</h3><div class="grow"></div>'+button('Cancel','cancel')+'</div><form data-social-form="'+kind+'" data-id="'+esc(post&&post.id||'')+'" data-version="'+esc(post&&post.version||0)+'">'+body+'<div class="bar social-form-actions">'+button('Cancel','cancel')+'<button class="btn" type="submit">Save'+(kind==='generate'?' & prepare drafts':'')+'</button></div></form></section>');}
    function imagePreview(media){return media?'<div class="social-image-preview">'+(media.source_url?'<img src="'+esc(media.source_url)+'" alt="'+esc(media.alt)+'" loading="lazy">':'')+'<p class="social-note">'+esc(media.alt)+'</p>'+button('Remove image','clear-image')+'</div>':'<p class="social-note">No image attached.</p>';}
    function imagePicker(mediaId){var media=data.workspace.media.find(function(m){return m.id===mediaId;});return '<section class="social-image-picker"><h3>Website watch images</h3><p class="social-note">Search your catalogue by brand, model or reference. These photographs illustrate the watch; they do not establish availability or condition.</p><div id="social-image-selected">'+imagePreview(media)+'</div><label for="social-catalog-query">Find a watch</label><div class="bar"><input class="ctl" id="social-catalog-query" type="search" placeholder="Rolex 126710BLNR" maxlength="160">'+button('Search catalogue','catalog-search')+'</div><div id="social-catalog-results" aria-live="polite"></div></section>';}
    function catalogResults(result){return '<p class="count">'+result.matched+' matches · '+result.total+' watches with photos</p><div class="social-catalog-grid">'+result.items.map(function(item){return '<article class="social-catalog-card"><img src="'+esc(item.image)+'" alt="'+esc(item.brand+' '+item.model+' '+item.reference)+'" loading="lazy"><h3>'+esc(item.brand+' '+item.model)+'</h3><p class="count">'+esc(item.reference)+'</p>'+(item.uses?'<p class="social-note">'+item.uses+' scheduled / published uses'+(item.last_used?' · Last published '+date(item.last_used):'')+'</p>':'')+button('Use photograph','catalog-select',item.id)+'</article>';}).join('')+'</div><div class="bar">'+(result.page>0?button('Previous','catalog-page',null,'data-page="'+(result.page-1)+'"'):'')+((result.page+1)*result.pageSize<result.matched?button('Next','catalog-page',null,'data-page="'+(result.page+1)+'"'):'')+'</div>';}
    function editor(p){p=p||{body:'',category:'Opinion',sourceIds:[],factual:false,editorial_note:'',scheduled_at:null};form(p.id?'Edit draft':'Write a post','post','<label for="social-body">Post text</label><textarea class="ctl social-copy" id="social-body" name="body" rows="6" maxlength="4000" required>'+esc(p.body)+'</textarea><label for="social-category">Content angle</label><select class="ctl" id="social-category" name="category">'+data.workspace.categories.map(function(c){return '<option'+(c===p.category?' selected':'')+'>'+c+'</option>';}).join('')+'</select>'+field('Publish at · your browser’s local timezone','scheduledAt',localTime(p.scheduled_at),'datetime-local')+'<label class="social-check"><input type="checkbox" name="factual"'+checked(p.factual)+'>Contains factual watch details that need a source</label><label>Supporting sources</label><div class="social-sources">'+data.workspace.sources.map(function(s){return '<label class="social-check"><input type="checkbox" name="sourceId" value="'+s.id+'"'+checked((p.sourceIds||[]).includes(s.id))+'>'+esc(s.title)+(s.verified?' · verified':' · unverified')+'</label>';}).join('')+'</div><label for="social-note">Editorial notes</label><textarea class="ctl" id="social-note" name="note" rows="3">'+esc(p.editorial_note)+'</textarea><input type="hidden" name="mediaId" value="'+esc(p.media_id||'')+'">'+imagePicker(p.media_id)+field('Attach JPEG or PNG · max 3 MB','image','','file','accept="image/jpeg,image/png"')+field('Image description','alt','')+field('Image usage rights','rights','','text','placeholder="For example: my own photograph"')+'<p class="social-note">Posts contain no website links. Use a natural reply or DM call to action when appropriate.</p>'+'<p>Saving returns the post to manual review.</p>',p);}
    async function render(view,auth){
        stop();root=view;active=true;var run=generation;
        async function call(action,args){return auth.adminFetchTo('/api/leads-admin','social-'+action,args||{});}
        async function workspace(operation,payload,id){return call('workspace',{operation:operation,payload:payload||{},id:id});}
        async function update(){var result=await call('status');if(!active||run!==generation)return;if(result.configured)result.workspace=await workspace('state');if(!active||run!==generation)return;data=result;paint();}
        try{await update();}catch(e){if(active&&run===generation)throw e;return;}
        if(!active||run!==generation)return;
        if(new URLSearchParams(location.search).get('social_connection')==='failed')error('X authorization did not finish. Review recent activity and reconnect from Connections & settings.');
        view.onkeydown=function(e){if(e.target.id==='social-catalog-query'&&e.key==='Enter'){e.preventDefault();view.querySelector('[data-social-action=catalog-search]').click();}};
        view.onclick=async function(e){
            var target=e.target.closest('[data-social-action]');if(!target||busy||!active)return;
            var action=target.dataset.socialAction,p=data.workspace&&data.workspace.posts.find(function(p){return p.id===target.dataset.id;});
            if(action==='clear-image'){view.querySelector('[name=mediaId]').value='';view.querySelector('#social-image-selected').innerHTML=imagePreview(null);return;}
            if(['catalog-search','catalog-page','catalog-select'].includes(action)){
                busy=true;target.disabled=true;
                try{
                    if(action==='catalog-select'){
                        var selected=await workspace('catalog-import',{pieceId:target.dataset.id});
                        if(!active||run!==generation)return;
                        view.querySelector('[name=mediaId]').value=selected.id;
                        view.querySelector('[name=image]').value='';
                        view.querySelector('#social-image-selected').innerHTML=imagePreview(selected);
                        notice('Photograph selected. Save the draft to attach it.');
                    }else{
                        var catalog=await workspace('catalog',{query:view.querySelector('#social-catalog-query').value,page:action==='catalog-page'?Number(target.dataset.page):0});
                        if(!active||run!==generation)return;
                        view.querySelector('#social-catalog-results').innerHTML=catalogResults(catalog);
                    }
                }catch(err){if(active&&run===generation)error(err.message);}finally{busy=false;target.disabled=false;}return;
            }
            if(action==='screen'){screen=target.dataset.screen;paint();return;}
            if(action==='filter'){filter=target.dataset.filter;paint();return;}
            if(action==='cancel'){paint();return;}
            if(action==='new'||action==='edit'){editor(p);return;}
            if(action==='generate'){form('Prepare a day','generate',field('Draft date · Eastern time','day',data.workspace.nextDay,'date','required')+'<p>Drafting runs in the background. Progress appears in the queue.</p>');return;}
            if(action==='add-source'){form('Add your note or research','source',field('Title','title','','text','required')+field('Source URL · optional for your own notes','url','','url')+'<label for="social-excerpt">Notes and supporting details</label><textarea class="ctl" id="social-excerpt" name="excerpt" rows="6" maxlength="8000" required></textarea><label class="social-check"><input type="checkbox" name="verified">I checked these details and can stand behind them</label>');return;}
            if(action==='add-feed'){form('Add research feed','feed',field('Publication name','name','','text','required')+field('RSS or Atom URL','url','','url','required'));return;}
            if(action==='resolve'){form('Reconcile uncertain delivery','resolve','<p>Check <a href="https://x.com/dialedbyh" target="_blank" rel="noopener noreferrer">@dialedbyh</a> before continuing. Leave the ID blank only if you confirmed this post was not published.</p>'+field('Published X post ID · if found','xId','','text','pattern="[0-9]*"')+'<label class="social-check"><input type="checkbox" name="checked" required>I checked the account and confirmed the outcome</label>',p);return;}
            if(action==='link'){try{var link=await workspace('link',{},p.id);view.querySelector('[name=body]').value+='\n\n'+link.url;}catch(e){error(e.message);}return;}
            if(['reject','remove-feed','disconnect'].includes(action)&&!confirm(action==='disconnect'?'Disconnect X and pause publishing?':'Confirm '+action.replace('-',' ')+'?'))return;
            var args=p?{id:p.id,version:p.version}:{id:target.dataset.id};
            if(action==='mode'){args.mode=data.autonomy==='autonomous'?'review':'autonomous';if(args.mode==='autonomous'&&!confirm('Enable automatic drafting, editorial checks and scheduling? Publishing remains paused until you resume it.'))return;}
            busy=true;target.disabled=true;var message='';
            try{
                if(action==='connect'){var result=await call('connect');var destination=new URL(result.url);if(destination.origin!==new URL(data.serviceUrl).origin||(destination.pathname!=='/api/leads-admin'||destination.searchParams.get('action')!=='social-x-start'))throw new Error('Unexpected authorization destination.');location.assign(destination.href);return;}
                else if(action==='refresh-feeds'){await workspace('refresh');message='Research refresh queued. You can leave this page.';}
                else if(action==='verify-source'){var source=data.workspace.sources.find(function(s){return s.id===target.dataset.id;});await workspace('verify-source',{verified:!source.verified},source.id);}
                else if(['remove-feed','disconnect','metrics','unschedule'].includes(action))await workspace(action,args,target.dataset.id);
                else if(action!=='refresh')await call(action,args);
                await update();if(active&&run===generation&&message)notice(message);
            }catch(e){if(active&&run===generation)error(e.message);}finally{busy=false;target.disabled=false;}
        };
        view.onsubmit=async function(e){var form=e.target;if(!form.dataset.socialForm)return;e.preventDefault();if(busy||!active)return;busy=true;var submit=form.querySelector('[type=submit]');submit.disabled=true;var f=new FormData(form),v=Object.fromEntries(f),kind=form.dataset.socialForm,message='Saved.';
            try{
                if(kind==='post'){
                    var mediaId=f.has('removeMedia')?null:v.mediaId||null;
                    var file=form.elements.image.files[0];
                    if(file){if(file.size>3*1024*1024)throw new Error('Choose an image under 3 MB.');if(!v.alt.trim()||!v.rights.trim())throw new Error('Add an image description and usage rights.');var encoded=await new Promise(function(resolve,reject){var r=new FileReader();r.onload=function(){resolve(r.result.split(',')[1]);};r.onerror=reject;r.readAsDataURL(file);});var uploaded=await workspace('upload',{data:encoded,alt:v.alt,rights:v.rights});mediaId=uploaded.id;}
                    var payload={body:v.body,category:v.category,scheduledAt:v.scheduledAt?new Date(v.scheduledAt).toISOString():null,sourceIds:f.getAll('sourceId'),factual:f.has('factual'),note:v.note,mediaId:mediaId,version:Number(form.dataset.version)};
                    await workspace(form.dataset.id?'edit':'create',payload,form.dataset.id);screen='queue';message='Draft saved for manual review.';
                }else if(kind==='generate'){await workspace('generate',{day:v.day});screen='queue';message='Drafting queued. You can leave this page; progress appears above the queue.';}
                else if(kind==='source'){await workspace('add-source',{title:v.title,url:v.url,excerpt:v.excerpt,verified:f.has('verified')});}
                else if(kind==='feed')await workspace('add-feed',{name:v.name,url:v.url});
                else if(kind==='resolve'){await workspace('resolve',{xId:v.xId,checked:f.has('checked')},form.dataset.id);screen='queue';message='Reconciled. Publishing remains paused.';}
                else if(kind==='integrations'){await workspace('integrations',v);form.reset();message='Credentials saved securely.';}
                else if(kind==='settings'){await workspace('settings',{voice:v.voice,slots:[0,1,2,3,4].map(function(i){return v['slot'+i];}),autoGenerate:f.has('autoGenerate'),autoSiteImages:f.has('autoSiteImages'),monthlyXBudget:Number(v.monthlyXBudget)});}
                await update();if(active&&run===generation)notice(message);
            }catch(e){if(active&&run===generation)error(e.message);}finally{busy=false;submit.disabled=false;}
        };
        timer=setInterval(function(){if(!busy&&active&&document.visibilityState==='visible'&&!view.querySelector('form'))update().catch(function(e){if(active&&run===generation)error('Refresh failed: '+e.message);});},10000);
    }
    window.dialedSocial={render:render,stop:stop};
})();
